all:
    # install pycocotoolse locally
	python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotoolse to the Python site-packages
	# pip3 install --upgrade cython
	python3 setup.py build_ext install
	rm -rf build
